# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Linking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Linking
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  
  pod 'SVProgressHUD'
  pod 'ActionSheetPicker-3.0'

  target 'LinkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LinkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
